// Auto-generated: registers ALL components as alpha-*
import './button/button.js';  // alpha-button (Tier 3 extended)
import './alert/alert.js';  // alpha-alert
import './animated-image/animated-image.js';  // alpha-animated-image
import './animation/animation.js';  // alpha-animation
import './avatar/avatar.js';  // alpha-avatar
import './badge/badge.js';  // alpha-badge
import './breadcrumb/breadcrumb.js';  // alpha-breadcrumb
import './breadcrumb-item/breadcrumb-item.js';  // alpha-breadcrumb-item
import './button-group/button-group.js';  // alpha-button-group
import './card/card.js';  // alpha-card
import './carousel/carousel.js';  // alpha-carousel
import './carousel-item/carousel-item.js';  // alpha-carousel-item
import './checkbox/checkbox.js';  // alpha-checkbox
import './color-picker/color-picker.js';  // alpha-color-picker
import './copy-button/copy-button.js';  // alpha-copy-button
import './details/details.js';  // alpha-details
import './dialog/dialog.js';  // alpha-dialog
import './divider/divider.js';  // alpha-divider
import './drawer/drawer.js';  // alpha-drawer
import './dropdown/dropdown.js';  // alpha-dropdown
import './format-bytes/format-bytes.js';  // alpha-format-bytes
import './format-date/format-date.js';  // alpha-format-date
import './format-number/format-number.js';  // alpha-format-number
import './icon/icon.js';  // alpha-icon
import './icon-button/icon-button.js';  // alpha-icon-button
import './image-comparer/image-comparer.js';  // alpha-image-comparer
import './include/include.js';  // alpha-include
import './input/input.js';  // alpha-input
import './menu/menu.js';  // alpha-menu
import './menu-item/menu-item.js';  // alpha-menu-item
import './menu-label/menu-label.js';  // alpha-menu-label
import './mutation-observer/mutation-observer.js';  // alpha-mutation-observer
import './option/option.js';  // alpha-option
import './popup/popup.js';  // alpha-popup
import './progress-bar/progress-bar.js';  // alpha-progress-bar
import './progress-ring/progress-ring.js';  // alpha-progress-ring
import './qr-code/qr-code.js';  // alpha-qr-code
import './radio/radio.js';  // alpha-radio
import './radio-button/radio-button.js';  // alpha-radio-button
import './radio-group/radio-group.js';  // alpha-radio-group
import './range/range.js';  // alpha-range
import './rating/rating.js';  // alpha-rating
import './relative-time/relative-time.js';  // alpha-relative-time
import './resize-observer/resize-observer.js';  // alpha-resize-observer
import './select/select.js';  // alpha-select
import './skeleton/skeleton.js';  // alpha-skeleton
import './spinner/spinner.js';  // alpha-spinner
import './split-panel/split-panel.js';  // alpha-split-panel
import './switch/switch.js';  // alpha-switch
import './tab/tab.js';  // alpha-tab
import './tab-group/tab-group.js';  // alpha-tab-group
import './tab-panel/tab-panel.js';  // alpha-tab-panel
import './tag/tag.js';  // alpha-tag
import './textarea/textarea.js';  // alpha-textarea
import './tooltip/tooltip.js';  // alpha-tooltip
import './tree/tree.js';  // alpha-tree
import './tree-item/tree-item.js';  // alpha-tree-item
import './visually-hidden/visually-hidden.js';  // alpha-visually-hidden
